version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:  
      - dbdata:/data/db   
    networks:
      - app-network  

  nodejs:
    image: node:12-alpine
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    networks:
      - app-network
    command: ./wait-for.sh mongo:27017 -- node index.js

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
